server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          #lb://cloud-payment-service gateway自动为我们创建的负载均衡uri
          uri: lb://cloud-payment-service #lb表示uri使用的协议，
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment-routh2  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #lb://cloud-payment-service gateway自动为我们创建的负载均衡uri
          uri: lb://cloud-payment-service #lb表示uri使用的协议，
          #相关断言参考官网
          predicates:
            - After=2020-11-25T23:24:37.444+08:00[Asia/Shanghai]
            - Path=/payment/lb/**   #断言，路径相匹配的进行路由
            - Cookie=username,zyp
          #将X-Request-red:blue标头添加到所有匹配请求的下游请求头中
          filters:
            - AddRequestHeader=X-Request-red, blue
        - id: baidu-routh #路由的ID，没有固定规则但要求唯一，将有配合服务名
          uri: https://news.baidu.com/guonei
          predicates:
            - Path=/guonei
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service


