server:
  port: 8402

spring:
  application:
    name: cloudalibaba-sentinel-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.115.112:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
#开启feign的日志功能
logging:
  level:
    com.zyp.springcloud.service.OpenFeignPaymentService: debug