server:
  port: 8002
eureka:
  client:
    #不注册进eureka服务注册中心
    register-with-eureka: false
    fetch-registry: true
    service-url:  #Map<String,String> 类型
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#设置OpenFeign客户端超时时间间隔(Openfeign默认支持ribbon)
ribbon:
  #建立连接后从服务器读取到可用资源所需的时间
  ReadTimeout: 5000
  #建立连接所用的时间，适用于网络状况正常情况下，两端连接所用的时间
  #ConnectTimeout: 5000
#开启feign的日志功能
logging:
  level:
    com.zyp.springcloud.service.OpenFeignPaymentService: debug
