server:
  port: 8005

spring:
  application:
    name: cloud-payment-consul
  cloud:
    #consul的配置地址
    consul:
      host: localhost
      port: 8500
      #注册的服务名
      discovery:
        service-name: ${spring.application.name}
