server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 123.56.115.112:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.115.112:3306/seata_order
    username: root
    password: 123456
#设置feign的超时时间
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyp.springcloud.domain
