server:
  port: 7001

spring:
  #热部署配置
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

#单机版eureka注册中心
#eureka:
  #instance:
    #hostname: localhost  #eureka服务端的实例名字
  #client:
    #register-with-eureka: false    #表示不向注册中心注册自己
    #fetch-registry: false  #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    #service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#集群版eureka注册中心
eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com/eureka/          #改为单机版，减少启动服务的等待时间
  #server:
    #enable-self-preservation: false   #关闭eureka的自我保护机制
    #eviction-interval-timer-in-ms: 2000 #剔除服务的时间间隔
